### ISSUE TITLE
Dungeon Icon text incorrect

### ISSUE THREAD

**Issue by Sythr4l** [NumyAddon/MythicPlusTweaks#2]
The dungeon icon text is not working properly for me.  See below - tooltip shows best tyrannical as 12 and fortified as 10, but the icon shows 12 for both.  Also, the icon numbers are incorrect based on the tooltip.

![MythicPlusTweaks issue](https://user-images.githubusercontent.com/113131440/211204892-9172a2cb-007f-43e8-ad7f-736ea61fff77.png)

**Comment by Numynum** [comment]
hi, it might not be fully clear which numbers are what 🙂 
basically, the top row is {best overall level} - {overall rating}
and the bottom row is {best affix level} - {affix rating}

which is why it's 12 - 227 and 12 - 118 for you 🙂 

the idea is that, in general, the most interesting stats when trying to improve your rating, is your overall rating, and your affix rating

**Comment by Sythr4l** [comment]
Oh that makes sense then.  My apologies!  I thought it was supposed to show both tyrannical and fortified entries.  Thanks for clarification!
