### ISSUE TITLE
Breaks keystone tooltip lines with icons/color

### ISSUE THREAD

**Issue by filliph** [NumyAddon/MythicPlusTweaks#3]
Without MPT enabled:
![image](https://github.com/NumyAddon/MythicPlusTweaks/assets/9424286/ca55d154-8b77-4e46-8c56-458aa6178c37)

With MPT enabled:
![image](https://github.com/NumyAddon/MythicPlusTweaks/assets/9424286/c8d6b04f-d94d-4238-9695-09b6451293fa)

I've confirmed this is due to the "Show score on keystone tooltip" setting. Even the example tooltip button works correctly if that setting is unticked. The tooltip line extractor does not like lines that have special data.

You can install my [ItemUpgradeTip](https://github.com/filliph/ItemUpgradeTip/) addon to see this bug in action.

Is there a reason why you decide to blanket replace all lines instead of just modifying the lines you need?

**Comment by Numynum** [comment]
I'll look into it 👍 

The main reason to replace all lines, is for the m+ tab, where I wanted to add/replace specific lines in a specific row
for keystone tooltips, this can be handled in a better way nowadays I think

**Comment by Numynum** [comment]
Actually I think it's because for whatever reason, I only look at the first 15 lines of the tooltip (no idea why I didn't handle that better)
which is why your first 2 lines (line 14 and 15) show up properly, but the 3rd, and the raiderio lines are cleared
(Presumably the addon adding the affix descriptions hooks after MPT does)

**Comment by Numynum** [comment]
thanks for letting me know, should be fixed next update 👌
