### ISSUE TITLE
[Feature Request] More obvious dungeon teleport cooldown

### ISSUE THREAD

**Issue by MSav93** [NumyAddon/MythicPlusTweaks#6]
This is kind of a multiple feature requests in one but they relate to the same thing, and that's making the dungeon teleport cooldown easier to see.

It would be convenient if I can see whether my dungeon teleports are on cooldown or not at a glance when I open the M+ window.
Currently they look identical when it's on cooldown or available to use (until you mouseover and see the red text)
![image](https://github.com/user-attachments/assets/934df0ee-136c-433f-9617-6ae66bd7ab7a)

So I have three suggestions to help with this:
1. Display the cooldown of the dungeon teleports as a swipe over the dungeon icons
2. Colour the blue shading over the dungeon teleport buttons red when on cooldown (probably not necessary if item 1 is implemented)
3. Have the number in the tooltip be dynamic and show the cooldown remaining instead of the total cooldown.

**Comment by Numynum** [comment]
somehow I didn't receive any notification for this 🤔 

in next version, the highlight is now shaded red when it's on cooldown

seems I never really noticed that the cooldown timer didn't tick down properly in the tooltip
it should now show the actual cooldown

since the cooldown is so stupidly long, I don't see much of a point adding a cooldown swipe, you'll never see it move
